// <auto-generated />
namespace SafeBarrio.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CrearContactosEmergencia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrearContactosEmergencia));
        
        string IMigrationMetadata.Id
        {
            get { return "202606230142061_CrearContactosEmergencia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
